/**
 * 
 * @type String Contiene el texto en español sobre las reglas del juego.
 */
var textRules=
       "Los jugadores seleccionan una de las opciones.\n"
       +"      El objetivo es vencer al oponente.\n"
       +"        Según las siguientes reglas las armas son:\n"
       +"<b>JUEGO DE 3:</b>\n"
       +"  • Tijeras cortan papel\n"
       +"  • Papel tapa piedra\n"
       +"  • Piedra aplasta tijeras\n\n"

       +"<b>JUEGO DE 5</b>\n"
       +"  • Tijeras cortan papel\n"
       +"  • Papel tapa piedra\n"
       +"  • Piedra aplasta Lagarto\n"
       +"  • Lagarto envenena a Spock\n"
       +"  • Spock rompe tijeras\n"
       +"  • Tijeras decapitan lagarto\n"
       +"  • Lagarto devora papel\n"
       +"  • Papel desautoriza Spock\n"
       +"  • Spock vaporiza piedra\n"
       +"  • Piedra aplasta tijeras\n\n"

       +"<b>JUEGO DE 9</b>\n"
       +"  • Piedra aplasta a la tijera\n"
       +"  • Piedra machaca a la esponja\n"
       +"  • Piedra machaca al humano\n"
       +"  • Piedra resiste al fuego\n"
       +"  • Tijera corta al papel\n"
       +"  • Tijera corta a la esponja\n"
       +"  • Tijera corta al humano\n"
       +"  • Tijera corta el aire\n"
       +"  • Fuego quema a las tijeras\n"
       +"  • Fuego quema al humano\n"
       +"  • Fuego quema a la esponja\n"
       +"  • Fuego quema al papel\n"
       +"  • Humano contamina el agua\n"
       +"  • Humano contamina el aire\n"
       +"  • Humano rompe el papel\n"
       +"  • Humano rompe la esponja\n"
       +"  • Esponja moja el papel\n"
       +"  • Esponja inutiliza la pistola\n"
       +"  • Esponja absorbe el agua\n"
       +"  • Esponja absorbe el aire\n"
       +"  • Papel contamina el aire\n"
       +"  • Papel contamina el agua\n"
       +"  • Papel inutiliza la pistola\n"
       +"  • Papel envuelve a la piedra\n"
       +"  • Aire apaga el fuego\n"
       +"  • Aire mueve agua\n"
       +"  • Aire oxida la pistola\n"
       +"  • Aire erosiona la piedra\n"
       +"  • Agua apaga el fuego\n"
       +"  • Agua inutiliza la pistola\n"
       +"  • Agua erosiona a la piedra\n"
       +"  • Agua oxida las tijeras\n"
       +"  • Pistola mata al humano\n"
       +"  • Pistola destroza las tijeras\n"
       +"  • Pistola destruye la piedra\n"
       +"  • Pistola apaga el fuego";
       
/**
 * 
 * @type String Contiene tel texto en inglés sobre las reglas del juego.
 */
var textRulesEng=
        "Players choose one of the options.\n"
        +"    The goal is to beat the opponent.\n"
        +"  According to the following rules you can win\n\n\
            on these situations:\n"
        +"<b>GAME OF 3:</b>\n"
        +"  • Scissors cuts Paper\n"
        +"  • Paper wraps Stone\n"
        +"  • Rock crushes Scissors\n\n"

        +"<b>GAME OF 5</b>\n"
        +"  • Scissors cuts Paper\n"
        +"  • Paper wraps Stone\n"
        +"  • Rock crushes Lizard\n"
        +"  • Lizard poisons Spock\n"
        +"  • Spock breaks Scissors\n"
        +"  • Scissors decapitate Lizard\n"
        +"  • Lizard eats Paper\n"
        +"  • Paper disproves Spock\n"
        +"  • Spock vaporizes Rock\n"
        +"  • Rock crushes Scissors\n"


        +"<b>GAME OF 9</b>\n"
        +"  • Rock crushes Scissors\n"
        +"  • Rock crushes Sponge\n"
        +"  • Rock crushes Human\n"
        +"  • Rock is Fire resistant\n"
        +"  • Scissors cuts Paper\n"
        +"  • Scissors cuts Sponge\n"
        +"  • Scissors cuts Human\n"
        +"  • Scissors cuts Air\n"
        +"  • Fire burns Scissors\n"
        +"  • Fire burns Human\n"
        +"  • Fire burns Sponge\n"
        +"  • Fire burns Paper\n"
        +"  • Human pollutes Water\n"
        +"  • Human pollutes Air\n"
        +"  • Human breaks Paper\n"
        +"  • Human breaks Sponge\n"
        +"  • Sponge wet Paper\n"
        +"  • Sponge knocked Gun\n"
        +"  • Sponge absorbs Water\n"
        +"  • Sponge absorbs Air\n"
        +"  • Paper pollutes Air\n"
        +"  • Paper pollutes Water\n"
        +"  • Paper knocked Gun\n"
        +"  • Paper wraps Stone\n"
        +"  • Air blows Fire\n"
        +"  • Air moves Water\n"
        +"  • Air oxidizes Gun\n"
        +"  • Air erodes Rock\n"
        +"  • Water extinguishes Fire\n"
        +"  • Water knocked Gun\n"
        +"  • Water erodes Rock\n"
        +"  • Water oxidized Scissors\n"
        +"  • Gun kills Human\n"
        +"  • Gun smashes Scissors\n"
        +"  • Gun destroys Rock\n"
        +"  • Gun turns Fire off";
